// [TODO] Code generated by "github.com/magicsong/generate-go-for-sonarqube", you should edit some validation logic here

package sonar

func (s *AlmIntegrationsService) ValidateCheckPatOpt(opt *AlmIntegrationsCheckPatOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateGetGithubClientIdOpt(opt *AlmIntegrationsGetGithubClientIdOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateImportAzureProjectOpt(opt *AlmIntegrationsImportAzureProjectOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateImportBitbucketcloudRepoOpt(opt *AlmIntegrationsImportBitbucketcloudRepoOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateImportBitbucketserverProjectOpt(opt *AlmIntegrationsImportBitbucketserverProjectOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateImportGithubProjectOpt(opt *AlmIntegrationsImportGithubProjectOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateImportGitlabProjectOpt(opt *AlmIntegrationsImportGitlabProjectOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateListAzureProjectsOpt(opt *AlmIntegrationsListAzureProjectsOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateListBitbucketserverProjectsOpt(opt *AlmIntegrationsListBitbucketserverProjectsOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateListGithubOrganizationsOpt(opt *AlmIntegrationsListGithubOrganizationsOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateListGithubRepositoriesOpt(opt *AlmIntegrationsListGithubRepositoriesOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateSearchAzureReposOpt(opt *AlmIntegrationsSearchAzureReposOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateSearchBitbucketcloudReposOpt(opt *AlmIntegrationsSearchBitbucketcloudReposOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateSearchBitbucketserverReposOpt(opt *AlmIntegrationsSearchBitbucketserverReposOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateSearchGitlabReposOpt(opt *AlmIntegrationsSearchGitlabReposOption) error {
	return nil
}
func (s *AlmIntegrationsService) ValidateSetPatOpt(opt *AlmIntegrationsSetPatOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateCountBindingOpt(opt *AlmSettingsCountBindingOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateCreateAzureOpt(opt *AlmSettingsCreateAzureOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateCreateBitbucketOpt(opt *AlmSettingsCreateBitbucketOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateCreateBitbucketcloudOpt(opt *AlmSettingsCreateBitbucketcloudOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateCreateGithubOpt(opt *AlmSettingsCreateGithubOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateCreateGitlabOpt(opt *AlmSettingsCreateGitlabOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateDeleteOpt(opt *AlmSettingsDeleteOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateDeleteBindingOpt(opt *AlmSettingsDeleteBindingOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateGetBindingOpt(opt *AlmSettingsGetBindingOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateListOpt(opt *AlmSettingsListOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateSetAzureBindingOpt(opt *AlmSettingsSetAzureBindingOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateSetBitbucketBindingOpt(opt *AlmSettingsSetBitbucketBindingOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateSetBitbucketcloudBindingOpt(opt *AlmSettingsSetBitbucketcloudBindingOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateSetGithubBindingOpt(opt *AlmSettingsSetGithubBindingOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateSetGitlabBindingOpt(opt *AlmSettingsSetGitlabBindingOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateUpdateAzureOpt(opt *AlmSettingsUpdateAzureOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateUpdateBitbucketOpt(opt *AlmSettingsUpdateBitbucketOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateUpdateBitbucketcloudOpt(opt *AlmSettingsUpdateBitbucketcloudOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateUpdateGithubOpt(opt *AlmSettingsUpdateGithubOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateUpdateGitlabOpt(opt *AlmSettingsUpdateGitlabOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateValidateOpt(opt *AlmSettingsValidateOption) error {
	return nil
}
func (s *AlmSettingsService) ValidateValidateBindingOpt(opt *AlmSettingsValidateBindingOption) error {
	return nil
}
func (s *AnalysisCacheService) ValidateClearOpt(opt *AnalysisCacheClearOption) error {
	return nil
}
func (s *AnalysisCacheService) ValidateGetOpt(opt *AnalysisCacheGetOption) error {
	return nil
}
func (s *AuthenticationService) ValidateLoginOpt(opt *AuthenticationLoginOption) error {
	return nil
}
func (s *CeService) ValidateActivityOpt(opt *CeActivityOption) error {
	return nil
}
func (s *CeService) ValidateActivityStatusOpt(opt *CeActivityStatusOption) error {
	return nil
}
func (s *CeService) ValidateAnalysisStatusOpt(opt *CeAnalysisStatusOption) error {
	return nil
}
func (s *CeService) ValidateCancelOpt(opt *CeCancelOption) error {
	return nil
}
func (s *CeService) ValidateComponentOpt(opt *CeComponentOption) error {
	return nil
}
func (s *CeService) ValidateDismissAnalysisWarningOpt(opt *CeDismissAnalysisWarningOption) error {
	return nil
}
func (s *CeService) ValidateSubmitOpt(opt *CeSubmitOption) error {
	return nil
}
func (s *CeService) ValidateTaskOpt(opt *CeTaskOption) error {
	return nil
}
func (s *ComponentsService) ValidateAppOpt(opt *ComponentsAppOption) error {
	return nil
}
func (s *ComponentsService) ValidateSearchOpt(opt *ComponentsSearchOption) error {
	return nil
}
func (s *ComponentsService) ValidateSearchProjectsOpt(opt *ComponentsSearchProjectsOption) error {
	return nil
}
func (s *ComponentsService) ValidateShowOpt(opt *ComponentsShowOption) error {
	return nil
}
func (s *ComponentsService) ValidateSuggestionsOpt(opt *ComponentsSuggestionsOption) error {
	return nil
}
func (s *ComponentsService) ValidateTreeOpt(opt *ComponentsTreeOption) error {
	return nil
}
func (s *DevelopersService) ValidateSearchEventsOpt(opt *DevelopersSearchEventsOption) error {
	return nil
}
func (s *DuplicationsService) ValidateShowOpt(opt *DuplicationsShowOption) error {
	return nil
}
func (s *EmailsService) ValidateSendOpt(opt *EmailsSendOption) error {
	return nil
}
func (s *FavoritesService) ValidateAddOpt(opt *FavoritesAddOption) error {
	return nil
}
func (s *FavoritesService) ValidateRemoveOpt(opt *FavoritesRemoveOption) error {
	return nil
}
func (s *FavoritesService) ValidateSearchOpt(opt *FavoritesSearchOption) error {
	return nil
}
func (s *HotspotsService) ValidateAddCommentOpt(opt *HotspotsAddCommentOption) error {
	return nil
}
func (s *HotspotsService) ValidateAssignOpt(opt *HotspotsAssignOption) error {
	return nil
}
func (s *HotspotsService) ValidateChangeStatusOpt(opt *HotspotsChangeStatusOption) error {
	return nil
}
func (s *HotspotsService) ValidateDeleteCommentOpt(opt *HotspotsDeleteCommentOption) error {
	return nil
}
func (s *HotspotsService) ValidateEditCommentOpt(opt *HotspotsEditCommentOption) error {
	return nil
}
func (s *HotspotsService) ValidateSearchOpt(opt *HotspotsSearchOption) error {
	return nil
}
func (s *HotspotsService) ValidateShowOpt(opt *HotspotsShowOption) error {
	return nil
}
func (s *IssuesService) ValidateAddCommentOpt(opt *IssuesAddCommentOption) error {
	return nil
}
func (s *IssuesService) ValidateAssignOpt(opt *IssuesAssignOption) error {
	return nil
}
func (s *IssuesService) ValidateAuthorsOpt(opt *IssuesAuthorsOption) error {
	return nil
}
func (s *IssuesService) ValidateBulkChangeOpt(opt *IssuesBulkChangeOption) error {
	return nil
}
func (s *IssuesService) ValidateChangelogOpt(opt *IssuesChangelogOption) error {
	return nil
}
func (s *IssuesService) ValidateComponentTagsOpt(opt *IssuesComponentTagsOption) error {
	return nil
}
func (s *IssuesService) ValidateDeleteCommentOpt(opt *IssuesDeleteCommentOption) error {
	return nil
}
func (s *IssuesService) ValidateDoTransitionOpt(opt *IssuesDoTransitionOption) error {
	return nil
}
func (s *IssuesService) ValidateEditCommentOpt(opt *IssuesEditCommentOption) error {
	return nil
}
func (s *IssuesService) ValidatePullOpt(opt *IssuesPullOption) error {
	return nil
}
func (s *IssuesService) ValidatePullTaintOpt(opt *IssuesPullTaintOption) error {
	return nil
}
func (s *IssuesService) ValidateReindexOpt(opt *IssuesReindexOption) error {
	return nil
}
func (s *IssuesService) ValidateSearchOpt(opt *IssuesSearchOption) error {
	return nil
}
func (s *IssuesService) ValidateSetSeverityOpt(opt *IssuesSetSeverityOption) error {
	return nil
}
func (s *IssuesService) ValidateSetTagsOpt(opt *IssuesSetTagsOption) error {
	return nil
}
func (s *IssuesService) ValidateSetTypeOpt(opt *IssuesSetTypeOption) error {
	return nil
}
func (s *IssuesService) ValidateTagsOpt(opt *IssuesTagsOption) error {
	return nil
}
func (s *L10NService) ValidateIndexOpt(opt *L10NIndexOption) error {
	return nil
}
func (s *LanguagesService) ValidateListOpt(opt *LanguagesListOption) error {
	return nil
}
func (s *MeasuresService) ValidateComponentOpt(opt *MeasuresComponentOption) error {
	return nil
}
func (s *MeasuresService) ValidateComponentTreeOpt(opt *MeasuresComponentTreeOption) error {
	return nil
}
func (s *MeasuresService) ValidateSearchOpt(opt *MeasuresSearchOption) error {
	return nil
}
func (s *MeasuresService) ValidateSearchHistoryOpt(opt *MeasuresSearchHistoryOption) error {
	return nil
}
func (s *MetricsService) ValidateSearchOpt(opt *MetricsSearchOption) error {
	return nil
}
func (s *NavigationService) ValidateComponentOpt(opt *NavigationComponentOption) error {
	return nil
}
func (s *NewCodePeriodsService) ValidateListOpt(opt *NewCodePeriodsListOption) error {
	return nil
}
func (s *NewCodePeriodsService) ValidateSetOpt(opt *NewCodePeriodsSetOption) error {
	return nil
}
func (s *NewCodePeriodsService) ValidateShowOpt(opt *NewCodePeriodsShowOption) error {
	return nil
}
func (s *NewCodePeriodsService) ValidateUnsetOpt(opt *NewCodePeriodsUnsetOption) error {
	return nil
}
func (s *NotificationsService) ValidateAddOpt(opt *NotificationsAddOption) error {
	return nil
}
func (s *NotificationsService) ValidateListOpt(opt *NotificationsListOption) error {
	return nil
}
func (s *NotificationsService) ValidateRemoveOpt(opt *NotificationsRemoveOption) error {
	return nil
}
func (s *PermissionsService) ValidateAddGroupOpt(opt *PermissionsAddGroupOption) error {
	return nil
}
func (s *PermissionsService) ValidateAddGroupToTemplateOpt(opt *PermissionsAddGroupToTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateAddProjectCreatorToTemplateOpt(opt *PermissionsAddProjectCreatorToTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateAddUserOpt(opt *PermissionsAddUserOption) error {
	return nil
}
func (s *PermissionsService) ValidateAddUserToTemplateOpt(opt *PermissionsAddUserToTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateApplyTemplateOpt(opt *PermissionsApplyTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateBulkApplyTemplateOpt(opt *PermissionsBulkApplyTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateCreateTemplateOpt(opt *PermissionsCreateTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateDeleteTemplateOpt(opt *PermissionsDeleteTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateGroupsOpt(opt *PermissionsGroupsOption) error {
	return nil
}
func (s *PermissionsService) ValidateRemoveGroupOpt(opt *PermissionsRemoveGroupOption) error {
	return nil
}
func (s *PermissionsService) ValidateRemoveGroupFromTemplateOpt(opt *PermissionsRemoveGroupFromTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateRemoveProjectCreatorFromTemplateOpt(opt *PermissionsRemoveProjectCreatorFromTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateRemoveUserOpt(opt *PermissionsRemoveUserOption) error {
	return nil
}
func (s *PermissionsService) ValidateRemoveUserFromTemplateOpt(opt *PermissionsRemoveUserFromTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateSearchTemplatesOpt(opt *PermissionsSearchTemplatesOption) error {
	return nil
}
func (s *PermissionsService) ValidateSetDefaultTemplateOpt(opt *PermissionsSetDefaultTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateTemplateGroupsOpt(opt *PermissionsTemplateGroupsOption) error {
	return nil
}
func (s *PermissionsService) ValidateTemplateUsersOpt(opt *PermissionsTemplateUsersOption) error {
	return nil
}
func (s *PermissionsService) ValidateUpdateTemplateOpt(opt *PermissionsUpdateTemplateOption) error {
	return nil
}
func (s *PermissionsService) ValidateUsersOpt(opt *PermissionsUsersOption) error {
	return nil
}
func (s *PluginsService) ValidateDownloadOpt(opt *PluginsDownloadOption) error {
	return nil
}
func (s *PluginsService) ValidateInstallOpt(opt *PluginsInstallOption) error {
	return nil
}
func (s *PluginsService) ValidateInstalledOpt(opt *PluginsInstalledOption) error {
	return nil
}
func (s *PluginsService) ValidateUninstallOpt(opt *PluginsUninstallOption) error {
	return nil
}
func (s *PluginsService) ValidateUpdateOpt(opt *PluginsUpdateOption) error {
	return nil
}
func (s *ProjectAnalysesService) ValidateCreateEventOpt(opt *ProjectAnalysesCreateEventOption) error {
	return nil
}
func (s *ProjectAnalysesService) ValidateDeleteOpt(opt *ProjectAnalysesDeleteOption) error {
	return nil
}
func (s *ProjectAnalysesService) ValidateDeleteEventOpt(opt *ProjectAnalysesDeleteEventOption) error {
	return nil
}
func (s *ProjectAnalysesService) ValidateSearchOpt(opt *ProjectAnalysesSearchOption) error {
	return nil
}
func (s *ProjectAnalysesService) ValidateSetBaselineOpt(opt *ProjectAnalysesSetBaselineOption) error {
	return nil
}
func (s *ProjectAnalysesService) ValidateUnsetBaselineOpt(opt *ProjectAnalysesUnsetBaselineOption) error {
	return nil
}
func (s *ProjectAnalysesService) ValidateUpdateEventOpt(opt *ProjectAnalysesUpdateEventOption) error {
	return nil
}
func (s *ProjectBadgesService) ValidateMeasureOpt(opt *ProjectBadgesMeasureOption) error {
	return nil
}
func (s *ProjectBadgesService) ValidateQualityGateOpt(opt *ProjectBadgesQualityGateOption) error {
	return nil
}
func (s *ProjectBadgesService) ValidateRenewTokenOpt(opt *ProjectBadgesRenewTokenOption) error {
	return nil
}
func (s *ProjectBadgesService) ValidateTokenOpt(opt *ProjectBadgesTokenOption) error {
	return nil
}
func (s *ProjectBranchesService) ValidateDeleteOpt(opt *ProjectBranchesDeleteOption) error {
	return nil
}
func (s *ProjectBranchesService) ValidateListOpt(opt *ProjectBranchesListOption) error {
	return nil
}
func (s *ProjectBranchesService) ValidateRenameOpt(opt *ProjectBranchesRenameOption) error {
	return nil
}
func (s *ProjectBranchesService) ValidateSetAutomaticDeletionProtectionOpt(opt *ProjectBranchesSetAutomaticDeletionProtectionOption) error {
	return nil
}
func (s *ProjectDumpService) ValidateExportOpt(opt *ProjectDumpExportOption) error {
	return nil
}
func (s *ProjectDumpService) ValidateStatusOpt(opt *ProjectDumpStatusOption) error {
	return nil
}
func (s *ProjectLinksService) ValidateCreateOpt(opt *ProjectLinksCreateOption) error {
	return nil
}
func (s *ProjectLinksService) ValidateDeleteOpt(opt *ProjectLinksDeleteOption) error {
	return nil
}
func (s *ProjectLinksService) ValidateSearchOpt(opt *ProjectLinksSearchOption) error {
	return nil
}
func (s *ProjectPullRequestsService) ValidateDeleteOpt(opt *ProjectPullRequestsDeleteOption) error {
	return nil
}
func (s *ProjectPullRequestsService) ValidateListOpt(opt *ProjectPullRequestsListOption) error {
	return nil
}
func (s *ProjectTagsService) ValidateSearchOpt(opt *ProjectTagsSearchOption) error {
	return nil
}
func (s *ProjectTagsService) ValidateSetOpt(opt *ProjectTagsSetOption) error {
	return nil
}
func (s *ProjectsService) ValidateBulkDeleteOpt(opt *ProjectsBulkDeleteOption) error {
	return nil
}
func (s *ProjectsService) ValidateCreateOpt(opt *ProjectsCreateOption) error {
	return nil
}
func (s *ProjectsService) ValidateDeleteOpt(opt *ProjectsDeleteOption) error {
	return nil
}
func (s *ProjectsService) ValidateSearchOpt(opt *ProjectsSearchOption) error {
	return nil
}
func (s *ProjectsService) ValidateSearchMyProjectsOpt(opt *ProjectsSearchMyProjectsOption) error {
	return nil
}
func (s *ProjectsService) ValidateSearchMyScannableProjectsOpt(opt *ProjectsSearchMyScannableProjectsOption) error {
	return nil
}
func (s *ProjectsService) ValidateUpdateDefaultVisibilityOpt(opt *ProjectsUpdateDefaultVisibilityOption) error {
	return nil
}
func (s *ProjectsService) ValidateUpdateKeyOpt(opt *ProjectsUpdateKeyOption) error {
	return nil
}
func (s *ProjectsService) ValidateUpdateVisibilityOpt(opt *ProjectsUpdateVisibilityOption) error {
	return nil
}
func (s *PushService) ValidateSonarlintEventsOpt(opt *PushSonarlintEventsOption) error {
	return nil
}
func (s *QualitygatesService) ValidateAddGroupOpt(opt *QualitygatesAddGroupOption) error {
	return nil
}
func (s *QualitygatesService) ValidateAddUserOpt(opt *QualitygatesAddUserOption) error {
	return nil
}
func (s *QualitygatesService) ValidateCopyOpt(opt *QualitygatesCopyOption) error {
	return nil
}
func (s *QualitygatesService) ValidateCreateOpt(opt *QualitygatesCreateOption) error {
	return nil
}
func (s *QualitygatesService) ValidateCreateConditionOpt(opt *QualitygatesCreateConditionOption) error {
	return nil
}
func (s *QualitygatesService) ValidateDeleteConditionOpt(opt *QualitygatesDeleteConditionOption) error {
	return nil
}
func (s *QualitygatesService) ValidateDeselectOpt(opt *QualitygatesDeselectOption) error {
	return nil
}
func (s *QualitygatesService) ValidateDestroyOpt(opt *QualitygatesDestroyOption) error {
	return nil
}
func (s *QualitygatesService) ValidateGetByProjectOpt(opt *QualitygatesGetByProjectOption) error {
	return nil
}
func (s *QualitygatesService) ValidateProjectStatusOpt(opt *QualitygatesProjectStatusOption) error {
	return nil
}
func (s *QualitygatesService) ValidateRemoveGroupOpt(opt *QualitygatesRemoveGroupOption) error {
	return nil
}
func (s *QualitygatesService) ValidateRemoveUserOpt(opt *QualitygatesRemoveUserOption) error {
	return nil
}
func (s *QualitygatesService) ValidateRenameOpt(opt *QualitygatesRenameOption) error {
	return nil
}
func (s *QualitygatesService) ValidateSearchOpt(opt *QualitygatesSearchOption) error {
	return nil
}
func (s *QualitygatesService) ValidateSearchGroupsOpt(opt *QualitygatesSearchGroupsOption) error {
	return nil
}
func (s *QualitygatesService) ValidateSearchUsersOpt(opt *QualitygatesSearchUsersOption) error {
	return nil
}
func (s *QualitygatesService) ValidateSelectOpt(opt *QualitygatesSelectOption) error {
	return nil
}
func (s *QualitygatesService) ValidateSetAsDefaultOpt(opt *QualitygatesSetAsDefaultOption) error {
	return nil
}
func (s *QualitygatesService) ValidateShowOpt(opt *QualitygatesShowOption) error {
	return nil
}
func (s *QualitygatesService) ValidateUpdateConditionOpt(opt *QualitygatesUpdateConditionOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateActivateRuleOpt(opt *QualityprofilesActivateRuleOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateActivateRulesOpt(opt *QualityprofilesActivateRulesOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateAddGroupOpt(opt *QualityprofilesAddGroupOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateAddProjectOpt(opt *QualityprofilesAddProjectOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateAddUserOpt(opt *QualityprofilesAddUserOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateBackupOpt(opt *QualityprofilesBackupOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateChangeParentOpt(opt *QualityprofilesChangeParentOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateChangelogOpt(opt *QualityprofilesChangelogOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateCompareOpt(opt *QualityprofilesCompareOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateCopyOpt(opt *QualityprofilesCopyOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateCreateOpt(opt *QualityprofilesCreateOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateDeactivateRuleOpt(opt *QualityprofilesDeactivateRuleOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateDeactivateRulesOpt(opt *QualityprofilesDeactivateRulesOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateDeleteOpt(opt *QualityprofilesDeleteOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateExportOpt(opt *QualityprofilesExportOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateInheritanceOpt(opt *QualityprofilesInheritanceOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateProjectsOpt(opt *QualityprofilesProjectsOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateRemoveGroupOpt(opt *QualityprofilesRemoveGroupOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateRemoveProjectOpt(opt *QualityprofilesRemoveProjectOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateRemoveUserOpt(opt *QualityprofilesRemoveUserOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateRenameOpt(opt *QualityprofilesRenameOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateRestoreOpt(opt *QualityprofilesRestoreOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateSearchOpt(opt *QualityprofilesSearchOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateSearchGroupsOpt(opt *QualityprofilesSearchGroupsOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateSearchUsersOpt(opt *QualityprofilesSearchUsersOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateSetDefaultOpt(opt *QualityprofilesSetDefaultOption) error {
	return nil
}
func (s *QualityprofilesService) ValidateShowOpt(opt *QualityprofilesShowOption) error {
	return nil
}
func (s *RulesService) ValidateCreateOpt(opt *RulesCreateOption) error {
	return nil
}
func (s *RulesService) ValidateDeleteOpt(opt *RulesDeleteOption) error {
	return nil
}
func (s *RulesService) ValidateRepositoriesOpt(opt *RulesRepositoriesOption) error {
	return nil
}
func (s *RulesService) ValidateSearchOpt(opt *RulesSearchOption) error {
	return nil
}
func (s *RulesService) ValidateShowOpt(opt *RulesShowOption) error {
	return nil
}
func (s *RulesService) ValidateTagsOpt(opt *RulesTagsOption) error {
	return nil
}
func (s *RulesService) ValidateUpdateOpt(opt *RulesUpdateOption) error {
	return nil
}
func (s *SettingsService) ValidateEncryptOpt(opt *SettingsEncryptOption) error {
	return nil
}
func (s *SettingsService) ValidateListDefinitionsOpt(opt *SettingsListDefinitionsOption) error {
	return nil
}
func (s *SettingsService) ValidateResetOpt(opt *SettingsResetOption) error {
	return nil
}
func (s *SettingsService) ValidateSetOpt(opt *SettingsSetOption) error {
	return nil
}
func (s *SettingsService) ValidateValuesOpt(opt *SettingsValuesOption) error {
	return nil
}
func (s *SourcesService) ValidateIndexOpt(opt *SourcesIndexOption) error {
	return nil
}
func (s *SourcesService) ValidateIssueSnippetsOpt(opt *SourcesIssueSnippetsOption) error {
	return nil
}
func (s *SourcesService) ValidateLinesOpt(opt *SourcesLinesOption) error {
	return nil
}
func (s *SourcesService) ValidateRawOpt(opt *SourcesRawOption) error {
	return nil
}
func (s *SourcesService) ValidateScmOpt(opt *SourcesScmOption) error {
	return nil
}
func (s *SourcesService) ValidateShowOpt(opt *SourcesShowOption) error {
	return nil
}
func (s *SystemService) ValidateChangeLogLevelOpt(opt *SystemChangeLogLevelOption) error {
	return nil
}
func (s *SystemService) ValidateLogsOpt(opt *SystemLogsOption) error {
	return nil
}
func (s *UserGroupsService) ValidateAddUserOpt(opt *UserGroupsAddUserOption) error {
	return nil
}
func (s *UserGroupsService) ValidateCreateOpt(opt *UserGroupsCreateOption) error {
	return nil
}
func (s *UserGroupsService) ValidateDeleteOpt(opt *UserGroupsDeleteOption) error {
	return nil
}
func (s *UserGroupsService) ValidateRemoveUserOpt(opt *UserGroupsRemoveUserOption) error {
	return nil
}
func (s *UserGroupsService) ValidateSearchOpt(opt *UserGroupsSearchOption) error {
	return nil
}
func (s *UserGroupsService) ValidateUpdateOpt(opt *UserGroupsUpdateOption) error {
	return nil
}
func (s *UserGroupsService) ValidateUsersOpt(opt *UserGroupsUsersOption) error {
	return nil
}
func (s *UserTokensService) ValidateGenerateOpt(opt *UserTokensGenerateOption) error {
	return nil
}
func (s *UserTokensService) ValidateRevokeOpt(opt *UserTokensRevokeOption) error {
	return nil
}
func (s *UserTokensService) ValidateSearchOpt(opt *UserTokensSearchOption) error {
	return nil
}
func (s *UsersService) ValidateAnonymizeOpt(opt *UsersAnonymizeOption) error {
	return nil
}
func (s *UsersService) ValidateChangePasswordOpt(opt *UsersChangePasswordOption) error {
	return nil
}
func (s *UsersService) ValidateCreateOpt(opt *UsersCreateOption) error {
	return nil
}
func (s *UsersService) ValidateDeactivateOpt(opt *UsersDeactivateOption) error {
	return nil
}
func (s *UsersService) ValidateDismissNoticeOpt(opt *UsersDismissNoticeOption) error {
	return nil
}
func (s *UsersService) ValidateGroupsOpt(opt *UsersGroupsOption) error {
	return nil
}
func (s *UsersService) ValidateSearchOpt(opt *UsersSearchOption) error {
	return nil
}
func (s *UsersService) ValidateSetHomepageOpt(opt *UsersSetHomepageOption) error {
	return nil
}
func (s *UsersService) ValidateUpdateOpt(opt *UsersUpdateOption) error {
	return nil
}
func (s *UsersService) ValidateUpdateIdentityProviderOpt(opt *UsersUpdateIdentityProviderOption) error {
	return nil
}
func (s *UsersService) ValidateUpdateLoginOpt(opt *UsersUpdateLoginOption) error {
	return nil
}
func (s *WebhooksService) ValidateCreateOpt(opt *WebhooksCreateOption) error {
	return nil
}
func (s *WebhooksService) ValidateDeleteOpt(opt *WebhooksDeleteOption) error {
	return nil
}
func (s *WebhooksService) ValidateDeliveriesOpt(opt *WebhooksDeliveriesOption) error {
	return nil
}
func (s *WebhooksService) ValidateDeliveryOpt(opt *WebhooksDeliveryOption) error {
	return nil
}
func (s *WebhooksService) ValidateListOpt(opt *WebhooksListOption) error {
	return nil
}
func (s *WebhooksService) ValidateUpdateOpt(opt *WebhooksUpdateOption) error {
	return nil
}
func (s *WebservicesService) ValidateListOpt(opt *WebservicesListOption) error {
	return nil
}
func (s *WebservicesService) ValidateResponseExampleOpt(opt *WebservicesResponseExampleOption) error {
	return nil
}
